CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Users" (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    username text NOT NULL,
    password text NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY (id)
);

CREATE TABLE "Boards" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Userid" integer,
    CONSTRAINT "PK_Boards" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Boards_Users_Userid" FOREIGN KEY ("Userid") REFERENCES "Users" (id)
);

CREATE TABLE "Columns" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "BoardId" integer,
    CONSTRAINT "PK_Columns" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Columns_Boards_BoardId" FOREIGN KEY ("BoardId") REFERENCES "Boards" ("Id")
);

CREATE TABLE "Notes" (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    content text,
    "isDone" boolean NOT NULL,
    date date NOT NULL,
    "ColumnId" integer NOT NULL,
    CONSTRAINT "PK_Notes" PRIMARY KEY (id),
    CONSTRAINT "FK_Notes_Columns_ColumnId" FOREIGN KEY ("ColumnId") REFERENCES "Columns" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Boards_Userid" ON "Boards" ("Userid");

CREATE INDEX "IX_Columns_BoardId" ON "Columns" ("BoardId");

CREATE INDEX "IX_Notes_ColumnId" ON "Notes" ("ColumnId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260410192842_InitialCreate', '10.0.5');

COMMIT;

START TRANSACTION;
ALTER TABLE "Boards" DROP CONSTRAINT "FK_Boards_Users_Userid";

ALTER TABLE "Columns" DROP CONSTRAINT "FK_Columns_Boards_BoardId";

ALTER TABLE "Boards" RENAME COLUMN "Userid" TO "UserId";

ALTER INDEX "IX_Boards_Userid" RENAME TO "IX_Boards_UserId";

UPDATE "Columns" SET "BoardId" = 0 WHERE "BoardId" IS NULL;
ALTER TABLE "Columns" ALTER COLUMN "BoardId" SET NOT NULL;
ALTER TABLE "Columns" ALTER COLUMN "BoardId" SET DEFAULT 0;

UPDATE "Boards" SET "UserId" = 0 WHERE "UserId" IS NULL;
ALTER TABLE "Boards" ALTER COLUMN "UserId" SET NOT NULL;
ALTER TABLE "Boards" ALTER COLUMN "UserId" SET DEFAULT 0;

ALTER TABLE "Boards" ADD CONSTRAINT "FK_Boards_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" (id) ON DELETE CASCADE;

ALTER TABLE "Columns" ADD CONSTRAINT "FK_Columns_Boards_BoardId" FOREIGN KEY ("BoardId") REFERENCES "Boards" ("Id") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260411075718_AddUserIdToBoard', '10.0.5');

COMMIT;

START TRANSACTION;
ALTER TABLE "Notes" RENAME COLUMN name TO "Name";

ALTER TABLE "Notes" RENAME COLUMN "isDone" TO "IsDone";

ALTER TABLE "Notes" RENAME COLUMN date TO "Date";

ALTER TABLE "Notes" RENAME COLUMN content TO "Content";

ALTER TABLE "Notes" RENAME COLUMN id TO "Id";

CREATE UNIQUE INDEX "IX_Users_username" ON "Users" (username);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260411143542_InitialChanges', '10.0.5');

COMMIT;

START TRANSACTION;
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260411165429_Init', '10.0.5');

COMMIT;

START TRANSACTION;
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260411165617_InitSupabase', '10.0.5');

COMMIT;

START TRANSACTION;
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260411165844_InitSupabase2', '10.0.5');

COMMIT;

START TRANSACTION;
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260411171357_InitSupabase3', '10.0.5');

COMMIT;

START TRANSACTION;
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260411172000_InitSupabase4', '10.0.5');

COMMIT;

START TRANSACTION;
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260411173011_InitSupabase5', '10.0.5');

COMMIT;

